## Numpy array and basics
learn about numpy

In [1]:
import numpy as np

### creating array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [4]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1, 2, 3]) # element wise multiplication
print("Python list multiplication", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python list multiplication [2 4 6]

 List operation time:  0.10037970542907715

 Numpy operation time:  0.011574029922485352


### creating array from scratch

In [9]:
zeros = np.zeros((3, 4))
print("Zeros array: \n ", zeros)

ones = np.ones((2, 3))
print("Ones array: \n ", ones)

full = np.full((2, 2), 7)
print("Full array: \n ", full)

random = np.random.random((2, 3))
print("Random array: \n ", random)

sequence = np.arange(0, 10, 2)
print("Sequence array: \n ", sequence)

Zeros array: 
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
  [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
  [[7 7]
 [7 7]]
Random array: 
  [[0.61824871 0.3610821  0.03590827]
 [0.94944046 0.83378211 0.98001099]]
Sequence array: 
  [0 2 4 6 8]


### vector, Matrix and Tensor