In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.random.rand(3, 3)
array3 = np.zeros((4, 4))

In [8]:
np.save('array1.npy', array1)
np.save('array2.npy', array2)
np.save('array3.npy', array3)

In [10]:
loaded_array1 = np.load('array1.npy')
loaded_array2 = np.load('array2.npy')
loaded_array3 = np.load('array3.npy')
print(loaded_array1)
print(loaded_array2)
print(loaded_array3)

[[1 2 3]
 [4 5 6]]
[[0.59860942 0.18516445 0.36678323]
 [0.32327598 0.00578824 0.17773222]
 [0.02911941 0.59200528 0.38083045]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
try:
    logo = np.load('numpy-logo.npy')

    # Display the logo
    plt.Figure(figsize=(10, 5))
    plt.Subplot(121)
    plt.imshow(logo)
    plt.title('NumPy Logo')
    plt.grid(False)

    dark_logo = 1 - logo
    plt.Subplot(122)
    plt.imshow(dark_logo)
    plt.title('Dark NumPy Logo')
    plt.grid(False)
except FileNotFoundError:
    print("File not found. Please check the file path and try again.")    

ValueError: This file contains pickled (object) data. If you trust the file you can load it unsafely using the `allow_pickle=` keyword argument or `pickle.load()`.